server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/todo_db
  jpa:
    hibernate:
      ddl-auto: none