server:
  port: 5000
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:root}
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_POST:3306}/${RDS_DB_NAME:todo_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect